production:
  dropbox:
    app_key: 57qro3k7fu03f1u
    app_secret: <%= ENV['DROPBOX_APP_SECRET'] %>
    access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>
    access_token_secret: <%= ENV['DROPBOX_ACCESS_TOKEN_SECRET'] %>
    user_id: <%= ENV['DROPBOX_USER_UD'] %>

  redis:
    url: <%= ENV['REDISTOGO_URL'] %>

  db:
    url: <%= ENV['DATABASE_URL'] %>
